export const metadata = {
    title: 'TV Shows',
    description: 'Generated by Next.js',
  }

import { Flex } from '@chakra-ui/react'
import { Providers } from './providers'
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode,
  }) {
    return (
      <html lang='en'>
        <head>
            <link rel="icon" type="image/png" href="tv_icon.png" />
        </head>
        <body>
          <Providers>
            <Flex direction='row' height='100%'>
              {children}
            </Flex>
          </Providers>
        </body>
      </html>
    )
  }